name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2

      - name: Get tag/version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Configure npm
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm config set @jbuncle:registry https://npm.pkg.github.com

      - run: npm config set git-tag-version false
      - run: npm version ${{ env.RELEASE_VERSION }}
      - run: npm pack
      - run: echo "RELEASE=$(ls *.tgz | tail -n 1)" >> $GITHUB_ENV
      - run: npm login --registry=https://npm.pkg.github.com --scope=@jbuncle
      - run: npm publish ${{ env.RELEASE }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}